* C-NOTE

C-NOTE is a file organization tool to help sort files that aren't easily sorted in directory hierarchies. C-NOTE uses a tagging system, to associate tags with entries; an entry can be a file, directory, or any valid filepath.

# TODO: Talk about .tag file

# TODO: Screenshots of basic use case


** Building

*** Dependencies

- [[https://cmake.org/download/][CMake]]
- A C++ Compiler ([[https://gcc.gnu.org/][~g++~]], [[https://visualstudio.microsoft.com/downloads/][~MSVC~]], even [[https://releases.llvm.org/download.html][~clang~]], etc.)
- [[https://git-scm.com/downloads][Git]]

*** Instructions

There are three ways to build this program on Linux and Windows:
1. Run `./build.sh` on Linux or `build.bat` on Windows. If you don't trust the script, just take a look at it before running it; it's like 10 LOC. This uses CMake automatically and generates a build system.
2. Use CMake, wait for it to do nothing, and PRAY that it hasn't crashed and it's actually just been downloading submodules for 30 minutes because your internet connection is trash
3. Run `git submodule update --init --recursive && cmake -B out && cmake --build out`.

If, by some evil and unfortunate twist of fate, you are using a mac, just er, idk, follow step 1, I guess. It's basically just unix anyway.
